name: Test Form
description: Test Form with an Action to Parse Issue
title: Test Form
labels: [ "test" ]
body:
  - type: input
    id: favorite_dish
    attributes:
      label: What's your favorite dish?
    validations:
      required: true

  - type: checkboxes
    id: favorite_color
    attributes:
      label:  What's your preferred color?
      options:
        - label: Red
        - label: Green
        - label: Blue

  - type: dropdown
    id: selected_var
    attributes:
      label: What variable do you want to lookup
      options: 
        - Foo
        - Lorem
    validations:
      required: true

  - type: input
    id: secret_name
    attributes:
      label: What secret do you want the value for?
    validations:
      required: true
