name: 'Issue Details'

on: 
  issues:
    types:
      - opened
      - edited
      - reopened

permissions:
  contents: read
  issues: write

jobs:
  process:
    name: Run
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'test')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse Issue Body
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v3
        with: 
          template-path: .github/ISSUE_TEMPLATE/my_template.yml

      - name: Debug Issue Parser Outputs
        run: |
          echo "Outputs: ${{ toJson(steps.issue-parser.outputs) }}"
          
      - run: echo $FAV_DISH
        env:
          FAV_DISH: ${{ steps.issue-parser.outputs.issueparser_favorite_dish }}
